### ISSUE TITLE
Multiple act_as in model roadmap

### ISSUE THREAD

**Issue by MasterBroki** [chaadow/active_record-acts_as#33]
Hi,

Is there a dev roadmap for getting this feature in the gem?

Thanks

**Comment by manuelmeurer** [comment]
I'm not actively working on this gem anymore, but I'd be happy to help with PRs or answer questions!

**Comment by MasterBroki** [comment]
Thanks! Maybe I could contribute a bit to the repo. Can you give me some pointers as of why this feature does not work? That would get me into the problem faster

**Comment by manuelmeurer** [comment]
I'm not sure what you mean. What exactly are you trying to do and what errors are you encountering?

**Comment by MasterBroki** [comment]
I'm talking about the known caveheat mentioned in the doc specifying that you can't put two act_as in the same class. For instance, If I have three tables Animals > Mammals > Canines and I create a Canine model that inherits Mammal that inherits Animals it throws an error. Let me know If you'd like a minimal reproduction of my issue

**Comment by manuelmeurer** [comment]
I'm not sure that what you describe is meant by "Multiple acts_as in the same class are not supported!". I think this is what (currently) won't work:

```
class MyApp::Product < ApplicationRecord
  actable inverse_of: :product
end

class MyApp::Thing < ApplicationRecord
  actable inverse_of: :product
end

class MyApp::Pen < ApplicationRecord
  acts_as :product, class_name: 'MyApp::Product'
  acts_as :thing, class_name: 'MyApp::Thing'
end
```

I'm not sure what exactly will happen if you try it, since I'm not the original author of this gem and I never tried using two `acts_as` in one model.
However, I'm sure it can be implemented without too much work.
I'd recommend to start with a failing test case and take it from there.
